/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-grid/demo/flickr-grid-layout.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../polymer/types/polymer.d.ts" />
/// <reference path="../../../iron-scroll-threshold/iron-scroll-threshold.d.ts" />
/// <reference path="../../../iron-ajax/iron-ajax.d.ts" />
/// <reference path="../../../paper-styles/shadow.d.ts" />
/// <reference path="../../../paper-spinner/paper-spinner.d.ts" />
/// <reference path="../../app-header-layout/app-header-layout.d.ts" />
/// <reference path="../../app-scroll-effects/effects/waterfall.d.ts" />
/// <reference path="../../app-header/app-header.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../app-grid-style.d.ts" />

interface XGridElement extends Polymer.Element {
  apiKey: string|null|undefined;
  photos: any[]|null|undefined;
  perPage: number|null|undefined;
  page: number|null|undefined;
  userId: string|null|undefined;
  totalPages: number|null|undefined;
  loadingPhotos: boolean|null|undefined;
  attached(): void;
  detached(): void;
  _getAPIEndpoint(apiKey: any, userId: any, page: any): any;
  _didReceiveResponse(e: any): void;
  _loadMorePhotos(): void;
  _getItemStyle(photo: any): any;
}

interface HTMLElementTagNameMap {
  "x-grid": XGridElement;
}
