/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-grid/demo/md-grid-layout.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../polymer/types/polymer.d.ts" />
/// <reference path="../../../iron-icons/iron-icons.d.ts" />
/// <reference path="../../../paper-styles/shadow.d.ts" />
/// <reference path="../../../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../../app-header-layout/app-header-layout.d.ts" />
/// <reference path="../../app-scroll-effects/effects/waterfall.d.ts" />
/// <reference path="../../app-header/app-header.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../app-grid-style.d.ts" />

interface XGridElement extends Polymer.Element {
  attached(): void;
  detached(): void;
}

interface HTMLElementTagNameMap {
  "x-grid": XGridElement;
}
