/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-grid/demo/simple-responsive-grid.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../polymer/types/polymer.d.ts" />
/// <reference path="../app-grid-style.d.ts" />

interface XAppElement extends Polymer.Element {
  attached(): void;
  detached(): void;
}

interface HTMLElementTagNameMap {
  "x-app": XAppElement;
}
