/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/pesto/src/recipe-app.html
 */

/// <reference path="recipe-detail.d.ts" />
/// <reference path="recipe-list.d.ts" />
/// <reference path="app-icons.d.ts" />

interface RecipeAppElement extends Polymer.Element {
  recipes: object|null|undefined;
  _route: object|null|undefined;
  _subRoute: object|null|undefined;
  _pageData: object|null|undefined;
  _selectedPage: string|null|undefined;
  _idData: object|null|undefined;
  _scrollPositionMap: object|null|undefined;
  attached(): void;
  _getRecipe(): any;
  _drawerSelected(): void;

  /**
   * Preserves the document scroll position, so
   * it can be restored when returning to a page.
   */
  _pageDataChanged(pageData: any, oldPageData: any): void;
}

interface HTMLElementTagNameMap {
  "recipe-app": RecipeAppElement;
}
