/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/pesto/src/recipe-detail.html
 */

interface RecipeDetailElement extends Polymer.Element {
  recipe: object|null|undefined;
}

interface HTMLElementTagNameMap {
  "recipe-detail": RecipeDetailElement;
}
