/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/pesto/src/recipe-list.html
 */

interface RecipeListElement extends Polymer.Element {
  recipes: object|null|undefined;
}

interface HTMLElementTagNameMap {
  "recipe-list": RecipeListElement;
}
