language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
script:
  - xvfb-run wct
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s ''default''; fi'
env:
  global:
    - secure: >-
        csKLT5uunJ3/FLpYcskgrQdRK7qCXtsq9OXnZpO99xTJXiWPJXwNzO1XDtsixBheI/YX++D4sTdVlBgNx6MIDJ4B8kTivPZIogtDn3CLOqkgZBNF3h0A6eGA6ynEyztp7kKUw6nRLgl/0vWVj8+MH7PTFjMi3YR6lFYfdCE6HsaFU75AP45BYZCb2KkeIXoXDYuPR3EVNwaZuqM5/MJ1nc32bpp4hk0/TZ8JKsAV8U6Y2hnlYM3uaimgkUwWMRbrgQoSSLys5SJACQirIO6nrbHqnNMLuiDLu1sozoLeoPlSQjb7HedDm9i9gEgKTzwjdOI1lC4M+vZxFmK6XP31AES1QERfVAiM1u6KFunpNZt28mXKndOQsjSiJaBbRbORy2QD5tpix4FxenFzp8JeVnmiryP+z9dFmu5Z4xLvhphCGG2Ox5Nf/W2Iif/V5Tu6VlXrlBc0qMZQ/CgoAkHWw+5mrQDvjC2ttCMrLIyQVNS0gwnR2gjPq+7etVUfH4gF0YtAHjebj2ag1G6j2sqnVlW6EVNmAFEo39gje4pTIxd5DwO4fKvEdtYRP4oxzJ4/49TKz/qQYltGcdK0hXuXRtuRiY6Wgip27iLE/G0YdVR1pwGCC0xSCzLP8pVE8iXzcVs/mNF6uHDT+p4Gsra5Zw+XpkQAMw5jRjT/OKKzqro=
    - secure: >-
        LYup6OydIBWkgTYpJB5yLGMWGynYlYc6lQrHM4x2LVFO07GR9Uz/q7o5dxzzJ3ggsJDQAKxdcyjlQWsJjhRhVa8VYn0X022poUk8i/oqgKFVHgs1ExF5jQOp7fKj0Qob8ANs3hXX3a768eR0yum8Kct9C69NQGvX4o1N1Y7u3IB776wsDHa+Jx4KT4YEIl46tBf0ZuV6HBDKjw5g1p7+MIfCPKCKYf2YGfbFymdmGByt6axLxB7JgtPZaPwzrathz6+U4JNI0g/r0us2kQeQ333bxu7kuhy6mALjYgytJFtScw3wQcQlq6Re0llG7GHOb9GLhFZdWXkFhMCHnwcPKtJXrakTyf35VK//GFuueMtPtI4ylT4LTXOkRZAHnSVNxhmoBz2D8PsjW+C6dmfyWR0I1RHQhpolH9Nmj5a2sK20D957t0ujCHSd1s4F7wLRMWRMNOAMjfeh7A6CwdoEHxHZ8SvWbGF4l5rur+Ct5Roxkbbgpmdh86s8EsITc7JTOQbIFqlMMbzCuSLoUaAcMfkZzraHUCtjOfBU8RA/K6B7jJNotpuFBZD3ZYPWPzwf1uKU0XjdiR23RAWskslcN/Nz+OwJVIF2f2t+qJvrUoJcFwqwOCD6LoqLUJfv0vooci5DADuzq+C14HXXPEsXgURzdNrqY8hZ9D65aUK0B6Y=
