language: node_js
sudo: 'false'
dist: trusty
node_js: '9'
addons:
  firefox: latest
  chrome: stable
before_script:
  - polymer lint
script:
  - polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
env:
  global:
    - secure: >-
        EEEMLLslkcsvJIvZR0qPbN59MfX+LD3tS+WQiOcb9cWc9OFa/HkN1FX5z3v+43e27cm63vIBw68XUOeewdinmDmts64hpAzd0H+q6QJFi3iLOztQqDPxi6L797No6nz25Q3p4X8pEk/kgkOFm+TW8Vn6CGWTJK56Oh48BSQSu2XsAns981eCsICjDNXhAMbqP0tJSBvoamSfcObNe1TnyH4WD7KKHvd58O8HzK2/EXLWkSpK+y5pAQWLXCYmyIEEthH63PAbTgRy+We5nrpIiTuscO5C3dssNXUCpaFBDeU8sV34Z5dp8dItDJPuLBP5pASroAH+wD/NTgeexcuzbfFuluTZ154pF+P2oJA0CYusGgTphtAtX76krdjpI0mtDJWAIrNLvwTlHxDq2aZtNA3EgnrulCLGF+KgV4FM+oe2VrYGt+kmLNKyW58VvqE51lnzZhqqufNEDYBK/P+QnVW2KlMoUKhpHAIbNR+m27NRuUB4ZICZd2G1/w6iFo01lTXPePG0hGlt+0ic7Ab3JpGSvBAjN58QlwPQ2oe8QF9lA47pyUN4lvYsB/50drA8VTVAbgT6oxxSxksR/AgRUA509ALfZvO4cOdcsjImNfwe763tVmJ9eCcAUFZZeoWqPWWzUrujk3q6oCnY+Lgtq8uzc3gBTiNaEw1KZBw7N48=
    - secure: >-
        X+MmATP7z3U/LLxDQ/rEaekqV0EoxYwoEbBJhBqXjnuHiaAdQlDWc2rDr+FIVWEMUTsDLodc3ujWwaRlIJhFecadIiudq2zdVB8IfJ8viDpSjZUCkXPa4+ufOyNDjm/zIJfoR7jY9TfjbvH98nt3m4xOxDBcVibdC82gryQhoYHiSAMeLY6vaTfvWOW810Iaey3vN4iolfhdc7zLkqAhPTv5hMnSx+HFVphMrgrs/WqGoQ4crNiTyQHtWrqzBAW413dtOEj3C7nIPYOVVwJuBNsPp1BVI0XX+RGufhPVcdfki8pTnjP0Svb5yeCekZeH4WIBCdpbhK+5J5PDbekxTiVvajWztDa8fzPlTeyCInheeQDhbGiixiQdgdHLOgeY8v4I/6OctBlqbFMMUGXBWHMGDK4TvVkniocGuQsmUfErlKFlfo9Tt/XZ1lRa3WUuSkfSpt+hc/7DFh6oMJjaOVFcKzHQsiqP48rwmm0/uy5A3F/kq3wDdPUIWZHgQLjL98b5I6DSH0vkKAkLBMn8fzfO0HZ+4cDu5hIACx2VtLPP4Y6/Sz1VDrPBsyr/1WQ1PtliVxHK+U60tIE6FOdiFT956zWMeW9epN4VmCJE0cAOGzwU/yuVojX4WQlhhXu9N/Nk0SrbIHpSajTLf3nemipIiNCfCy2c6Niw1zMXEDQ=
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
