language: node_js
sudo: 'false'
dist: trusty
node_js: '9'
addons:
  firefox: latest
  chrome: stable
before_script:
  - polymer lint
script:
  - polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
env:
  global:
    - secure: >-
        instsfyShhvUyJjnfz7Dn44pmOVLghQvkJ9FkxENvn6uatqzFrz/etQTo8IHUacp5MH9D4x1LA4Jxy7oq5Z1O8krsuFoFVeRc6xHSXo/KGcKz4CAc8y5RQKOIBa9DbTDlhwnO7T5W0cqm+67DvXJPt4Z+xDwim18hcd6XtZeNiVjq1uJbbkiRM2HVry0K4DuyjnLLdJABbBVEedyK62NxKV8Fuj+tifhYOGdtKN0o5ga107ZFQ8j22XaXz0EGib8ZeHPC7I4vLRqytwLqziu5Y0iBbyupGOyUczVc3leUa04NiUGlIzvN6CA76TMe65fRo7WKSmzKMcbOb3/464WcuXzU0UlGWEFfRzvmtquOKUQt6+9rEzaNXE0sEni5YCN/QC98Rql/gXCfu66nBSKULsiD0dln7qkV/Kfi730iRmyHyinVyEGIwfl/46vwlEreQHYgsbBGpy8EgmFA01Fw/8d389C4hNEaHRukcu6XLLA1aYppD7aYNjtQMdbh5kq3TQK+feJdC+DZ8OmM0EUox77ZbUnZEHztFt6N7Hbu4xusV2fhVBkOyrw7dPUkleRZQss4s6skAYFIXIvX5KnwNNaD/vHugHfH3AniM/SYc0KVa42Q2hCJytD3qE9kcIwsT8ikaWs4NSLwVRaTfBgEx9Q510425cOf/MXOkUmWkA=
    - secure: >-
        RqoXhbhdID8dSV+AYWnkqsYQOMyIvrF9eHiYh2Rk+k+MdpfclhmAz9b92Pe81xos/i7pAvwjDtLUTrWRBh22aWGHJXmN+MQSa7K8Cqx5mOE4NH7taAeH1QNaWcnseNoY+qAPYQ8fRVH8dxNq6FPeAwODKFiA6A8A6a/+hv8JahaKd/MePQOLEO+nUkeiTC/3nvsyGuZVuqt1323wjnCXeuizl0IM6FjhAb3Ml8ZEJUASW5N+6DiJJSu5znzHtZuhPgY/XIG8trhNklkfWo+5krkGWGl2XHvYkd1XOxWriHjCQxHWSu8z0NUyjrXw/gvjtRob+YYtGo2q+tP8eo0THUQe45ODdis80kVTFE7RlFcBU06N5T1or4HYPtCUHgSyv6VZmCHhOXalkYE63vjCizU99qEhh2djVJ7r9hFRe/kYyhyZw/lnQZpf0kCpkh1UQa1wai03Po53s4pj72qgN92NSjHm+soZnZSgE8gKY7RYHB/S3uB/w35dBDtn5OFcDdsc8zRjqHFmD61U/t3VVpdklL+nmwLew3Yq7ETpKEY4jy0VicIwcC3UFt7I2FLiDDy20fsoF3furbADMbsIbvUHbnmFoi+B3QGnzHPm98e0P9qBshduYS7Tmsqf9DqyyKPorf1YQB6/dsuo6MfQSk3Pi5XRFIUNF2341gTV5Wo=
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
