language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: RwxjX/xUyilPi+fnNLGJwOFL5pGIo/jlopkIM8Ic3L/+YClCbNLhIxMGCFML/qV94GZo8lxz8XhiTanLQLp3rpLQ+9QZNKNn6twkMg8xsZFs0URpCBZ+mTfM+QWYF6BWC1azJ8wm7k6diJ8WdicOH19yHYePYii7k6J3EbKzM8LOP2qe6YRH+4lsZBDJH+WiQfaT+/BhqrLuG7e9FiQg3uNAQsymJPeKmkpoBiBJMgn7ImmMZqyd3fo1sdEJrLjFk3y2eNBB9fhtiOJeRPHCfsZ51KlUS5V0zYpptLTXDpZ/6Zbcnwfz6XLvGkj+rCjyJivImwhGTo8OmITAz5Z8K1uAdoxvpBlJYh6YA0mj/RPHWMRenI3Ud/PrhE/4Y3dSwOqr5zDnu+vxChjWK7X2xUn3NXt+Lcuy7fpTCNPH4DrXZ7SeEmbQ6kN9WNINUP2U9Uvp1apqg4YvzdL9XGq0K38SlfupstrHJwDhfsGEqMasbSGqDAgzP1Gmh10ygPGa+5C6sqvbRBYoG21hSCu7Jtwj73mhz+marSLag5KTe3Zzi1ufoRFQnnVkk+4wse502WKQvf7Av4rMHiXx9zmxof329m5nuo20RxPCFGra7DiqqREE4qZMnNkA37MzW6TzGGoCFMGQHjtmXK6OH0tg5pYFmZ3z8lV6jdgWagzySD4=
  - secure: EKObsJc/nk+glQSoMzpKBOSZAgVp9siaL8D0gDtJaYGPy5STU0ffyjpB/0+zBRXsR6qHS+QhFnUSlCICif4OiDbFvwIT9cgIuR2PBSa72wIszU3m0/KLuIuJ6t0GSQY/P9OXpYT+UA0WxY2bMZFntvmvIyXiFSoq5fi8+EwC2gPcqJkD00W+2rZ1PC+a6m6MqaLolGUTxiz1qqvaGxxHM/NtPDyz6sZG6PHpBm6A+mr1+KY+RwmcueMSXWmZqe6MJd8ehinTapR1SIQEQvlB+IFrHmexpH623X6/pWqUEY/UZwRiPRyxWsDdou+Je6j1yJbNTfKK16W6JmBNa5eJdfbBI5d9Es5wYEM+dMdDs3BOkR/4m0wIP6H9QYyTmZz1QlRQK0Grr+6y7BHaPOoFCJ2n4LfbvPzS+SV2E2bfWU9TzZ/fmkuH1ZNljBtDr1X3TOPFkpqIIWVUCyjA/B+S9vqW4bElU28oc5voAxjYQz6xdggXzljK2CeMfWKqTD3dnb/bPHuIxBMrVEiYFndPu1bR94gUZQdesjTrUsoxLqrI6VznOaUInbK6Bd2XV+A44WFFH5bjWgLei/wM6bjgmA/jZk9Yoa4XFxDDDPubzEKzy9so392kM1mGUmekdrQIBAmKNLAcg/feiPU66EeDc/vOYQAjStrMRUyHTsOxMOU=
