/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-layout.html
 */

/// <reference path="helpers/helpers.d.ts" />
/// <reference path="app-drawer/app-drawer.d.ts" />
/// <reference path="app-drawer-layout/app-drawer-layout.d.ts" />
/// <reference path="app-grid/app-grid-style.d.ts" />
/// <reference path="app-header/app-header.d.ts" />
/// <reference path="app-header-layout/app-header-layout.d.ts" />
/// <reference path="app-toolbar/app-toolbar.d.ts" />
/// <reference path="app-box/app-box.d.ts" />

