/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   docs.html
 */

/// <reference path="../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../iron-component-page/iron-component-page.d.ts" />

