/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-scroll-effects/test/fade-background.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../web-component-tester/browser.d.ts" />
/// <reference path="../../../test-fixture/test-fixture-mocha.d.ts" />
/// <reference path="../../../test-fixture/test-fixture.d.ts" />
/// <reference path="../app-scroll-effects.d.ts" />
/// <reference path="x-container.d.ts" />
/// <reference path="utils.d.ts" />

