/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-scroll-effects/test/x-container.html
 */

/// <reference path="../../../polymer/types/polymer.d.ts" />
/// <reference path="../app-scroll-effects-behavior.d.ts" />

interface XContainerElement extends Polymer.Element, Polymer.AppScrollEffectsBehavior {
  shadow: boolean|null|undefined;
  _updateScrollState(scrollTop: any): void;
  _getDOMRef(id: any): any;
  _xScrollEffectChanged(): void;
}

interface HTMLElementTagNameMap {
  "x-container": XContainerElement;
}
