/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/publishing/src/article-detail.html
 */

/// <reference path="app-icons.d.ts" />

interface ArticleDetailElement extends Polymer.Element {
  article: object|null|undefined;
}

interface HTMLElementTagNameMap {
  "article-detail": ArticleDetailElement;
}
