/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/publishing/src/article-headline.html
 */

interface ArticleHeadlineElement extends Polymer.Element {
  article: object|null|undefined;
  href: string|null|undefined;
}

interface HTMLElementTagNameMap {
  "article-headline": ArticleHeadlineElement;
}
