/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/publishing/src/blog-app.html
 */

/// <reference path="app-icons.d.ts" />
/// <reference path="article-headline.d.ts" />
/// <reference path="article-detail.d.ts" />
/// <reference path="two-columns-grid.d.ts" />

interface BlogAppElement extends Polymer.Element {

  /**
   * Articles data.
   */
  articles: object|null|undefined;
  route: object|null|undefined;
  subRoute: object|null|undefined;
  subsubRoute: object|null|undefined;
  categoryData: object|null|undefined;
  pageData: object|null|undefined;
  idData: object|null|undefined;
  _scrollPositionMap: object|null|undefined;
  attached(): void;
  _equal(value1: any, value2: any): any;
  _updateArticle(articles: any, category: any, id: any): void;
  _drawerSelected(): void;
  _shouldHideMenuButton(page: any, narrow: any): any;

  /**
   * Preserves the document scroll position, so
   * it can be restored when returning to a page.
   */
  _subsubrouteChanged(subroute: any, oldSubroute: any): void;
}

interface HTMLElementTagNameMap {
  "blog-app": BlogAppElement;
}
