/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/publishing/src/two-columns-grid.html
 */

/**
 * This is a simple adaptive 2-columns grid. The first and every 4th item have width:100%, and the
 * rest of the items have width equals to the column width (`columnWidth` in px). The grid will reflow
 * to single column when 2 columns (plus a defined gutter margin) no longer fit on screen.
 *
 *     <two-columns-grid column-width="320" gutter="16">
 *       <div class="card"></div>
 *       <div class="card"></div>
 *       <div class="card"></div>
 *       <div class="card"></div>
 *       <div class="card"></div>
 *     </two-columns-grid>
 */
interface TwoColumnsGridElement extends Polymer.Element {

  /**
   * The width of the column in px.
   */
  columnWidth: number|null|undefined;

  /**
   * The gutter width in px.
   */
  gutter: number|null|undefined;

  /**
   * Indicates it is in narrow layout which means the grid is displayed as single column.
   */
  narrowLayout: boolean|null|undefined;
  attached(): void;
  _updateLayout(columnWidth: any, gutter: any): void;
  _updateCustomStyles(): void;
}

interface HTMLElementTagNameMap {
  "two-columns-grid": TwoColumnsGridElement;
}
