/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-drawer/demo/right-drawer.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../font-roboto/roboto.d.ts" />
/// <reference path="../../../iron-icons/iron-icons.d.ts" />
/// <reference path="../../../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../../../paper-item/paper-icon-item.d.ts" />
/// <reference path="../../demo/sample-content.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../app-drawer.d.ts" />

