/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   patterns/transform-navigation/x-app.html
 */

/// <reference path="../../app-drawer-layout/app-drawer-layout.d.ts" />
/// <reference path="../../app-drawer/app-drawer.d.ts" />
/// <reference path="../../app-header/app-header.d.ts" />
/// <reference path="../../app-header-layout/app-header-layout.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../../../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../../../iron-icons/iron-icons.d.ts" />
/// <reference path="../../../iron-media-query/iron-media-query.d.ts" />
/// <reference path="../../../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../../../paper-item/paper-item.d.ts" />
/// <reference path="../../../paper-listbox/paper-listbox.d.ts" />
/// <reference path="../../../paper-tabs/paper-tabs.d.ts" />

interface XAppElement extends Polymer.Element {
  selected: string|null|undefined;
  wideLayout: boolean|null|undefined;
  items: any[]|null|undefined;
  onLayoutChange(wide: any): void;
}

interface HTMLElementTagNameMap {
  "x-app": XAppElement;
}
