/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-drawer-layout/test/app-drawer-layout.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../web-component-tester/browser.d.ts" />
/// <reference path="../../../test-fixture/test-fixture-mocha.d.ts" />
/// <reference path="../../../iron-resizable-behavior/iron-resizable-behavior.d.ts" />
/// <reference path="../../../test-fixture/test-fixture.d.ts" />
/// <reference path="../../app-drawer/app-drawer.d.ts" />
/// <reference path="../app-drawer-layout.d.ts" />

interface XResizeableElement extends Polymer.Element, Polymer.IronResizableBehavior {
}

interface HTMLElementTagNameMap {
  "x-resizeable": XResizeableElement;
}
