/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-layout-behavior/app-layout-behavior.html
 */

/// <reference path="../../polymer/types/polymer.d.ts" />
/// <reference path="../../iron-resizable-behavior/iron-resizable-behavior.d.ts" />

declare namespace Polymer {

  interface AppLayoutBehavior extends Polymer.IronResizableBehavior {
    attached(): void;
    _appResetLayoutHandler(e: any): void;
    _updateLayoutStates(): void;

    /**
     * Resets the layout. If you changed the size of this element via CSS
     * you can notify the changes by either firing the `iron-resize` event
     * or calling `resetLayout` directly.
     */
    resetLayout(): void;
    _notifyLayoutChanged(): void;
    _notifyDescendantResize(): void;
  }

  const AppLayoutBehavior: object;
}
