/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-drawer/test/app-drawer.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../web-component-tester/browser.d.ts" />
/// <reference path="../../../test-fixture/test-fixture-mocha.d.ts" />
/// <reference path="../../../polymer/types/polymer.d.ts" />
/// <reference path="../../../test-fixture/test-fixture.d.ts" />
/// <reference path="../app-drawer.d.ts" />

