/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-toolbar/demo/index.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../font-roboto/roboto.d.ts" />
/// <reference path="../../../iron-icons/iron-icons.d.ts" />
/// <reference path="../../../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../../../paper-progress/paper-progress.d.ts" />
/// <reference path="../app-toolbar.d.ts" />

