/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   patterns/md-responsive-toolbar/index.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../font-roboto/roboto.d.ts" />
/// <reference path="../../../iron-icons/iron-icons.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../../../paper-icon-button/paper-icon-button.d.ts" />

