/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-scroll-effects/effects/material.html
 */

/// <reference path="../app-scroll-effects-behavior.d.ts" />
/// <reference path="waterfall.d.ts" />
/// <reference path="resize-title.d.ts" />
/// <reference path="blend-background.d.ts" />
/// <reference path="parallax-background.d.ts" />

