/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-scroll-effects/effects/parallax-background.html
 */

/// <reference path="../app-scroll-effects-behavior.d.ts" />

