/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/shrine/src/shrine-app.html
 */

/// <reference path="shrine-list.d.ts" />
/// <reference path="shrine-detail.d.ts" />

interface ShrineAppElement extends Polymer.Element {
  sections: any[]|null|undefined;
  readonly selectedTab: number|null|undefined;
  items: any[]|null|undefined;
  featuredItems: any[]|null|undefined;
  readonly page: string|null|undefined;
  route: object|null|undefined;
  subRoute: object|null|undefined;
  sectionData: object|null|undefined;
  idData: object|null|undefined;
  onDetailPage: boolean|null|undefined;
  attached(): void;
  _computeSelectedTab(sections: any, section: any): any;
  _getItemsCopy(items: any): any;
  _getFeaturedItem(featuredItems: any, section: any): any;
  _getDetailItem(items: any, id: any): any;
  _computePage(onDetailPage: any): any;
  _hashDidChange(): void;
  _equal(a: any, b: any): any;
  _getSectionClass(index: any, selectedTab: any): any;
  _shouldShowTabs(onDetailPage: any, smallScreen: any): any;
}

interface HTMLElementTagNameMap {
  "shrine-app": ShrineAppElement;
}
