/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/shrine/src/shrine-simple-item.html
 */

interface ShrineSimpleItemElement extends Polymer.Element {
  item: object|null|undefined;
}

interface HTMLElementTagNameMap {
  "shrine-simple-item": ShrineSimpleItemElement;
}
