/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/shrine/src/shrine-list.html
 */

/// <reference path="shrine-item.d.ts" />
/// <reference path="shrine-featured-item.d.ts" />

interface ShrineListElement extends Polymer.Element {
  items: any[]|null|undefined;
  featuredItem: object|null|undefined;
  section: string|null|undefined;
  _sortItems(): any;
}

interface HTMLElementTagNameMap {
  "shrine-list": ShrineListElement;
}
