/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/shrine/src/shrine-featured-item.html
 */

interface ShrineFeaturedItemElement extends Polymer.Element {
  item: object|null|undefined;
  _itemChanged(item: any): void;
}

interface HTMLElementTagNameMap {
  "shrine-featured-item": ShrineFeaturedItemElement;
}
