/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/shrine/src/shrine-detail.html
 */

/// <reference path="shrine-simple-item.d.ts" />

interface ShrineDetailElement extends Polymer.Element {
  item: object|null|undefined;
  section: string|null|undefined;
  relatedItems: any[]|null|undefined;
  _itemChanged(item: any): void;
}

interface HTMLElementTagNameMap {
  "shrine-detail": ShrineDetailElement;
}
