/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/landing-page/x-app.html
 */

interface XAppElement extends Polymer.Element {
}

interface HTMLElementTagNameMap {
  "x-app": XAppElement;
}
