/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   templates/test-drive/test-app.html
 */

interface TestAppElement extends Polymer.Element {
  condenses: boolean|null|undefined;
  fixed: boolean|null|undefined;
  reveals: boolean|null|undefined;
  shadow: boolean|null|undefined;
  blendBackground: boolean|null|undefined;
  fadeBackground: boolean|null|undefined;
  parallaxBackground: boolean|null|undefined;
  resizeSnappedTitle: boolean|null|undefined;
  resizeTitle: boolean|null|undefined;
  waterfall: boolean|null|undefined;
  _computeEffects(): any;
  _removeIf(propName: any, value: any): void;
}

interface HTMLElementTagNameMap {
  "test-app": TestAppElement;
}
