/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-header-layout/test/app-header-layout.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../web-component-tester/browser.d.ts" />
/// <reference path="../../../test-fixture/test-fixture-mocha.d.ts" />
/// <reference path="../../../test-fixture/test-fixture.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../../app-header/app-header.d.ts" />
/// <reference path="../app-header-layout.d.ts" />

