/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-header-layout/test/index.html
 */

/// <reference path="../../../web-component-tester/browser.d.ts" />

