/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-scroll-effects/app-scroll-effects.html
 */

/// <reference path="effects/blend-background.d.ts" />
/// <reference path="effects/fade-background.d.ts" />
/// <reference path="effects/material.d.ts" />
/// <reference path="effects/parallax-background.d.ts" />
/// <reference path="effects/resize-snapped-title.d.ts" />
/// <reference path="effects/resize-title.d.ts" />
/// <reference path="effects/waterfall.d.ts" />

