/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-box/demo/document-scroll.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../../demo/sample-content.d.ts" />
/// <reference path="../../app-scroll-effects/effects/parallax-background.d.ts" />
/// <reference path="../app-box.d.ts" />

