/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   app-header/demo/notes.html
 */

/// <reference path="../../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../../iron-icons/iron-icons.d.ts" />
/// <reference path="../../../iron-icon/iron-icon.d.ts" />
/// <reference path="../../../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../../../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../../../paper-fab/paper-fab.d.ts" />
/// <reference path="../../app-toolbar/app-toolbar.d.ts" />
/// <reference path="../../app-scroll-effects/app-scroll-effects.d.ts" />
/// <reference path="../app-header.d.ts" />

